// Generated by CoffeeScript 1.6.3
(function() {
  var Retailer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Retailer = (function() {
    function Retailer(name, country) {
      this.country = country;
      this.name = name + " " + this.country;
    }

    Retailer.prototype.clearCart = function(ref) {
      return console.log(ref.name + " cart cleared.");
    };

    return Retailer;

  })();

  this.Digikey = (function(_super) {
    __extends(Digikey, _super);

    function Digikey(country) {
      var data, xhr;
      xhr = new XMLHttpRequest();
      xhr.open("GET", chrome.extension.getURL("/data/digikey_international.json"), false);
      xhr.send();
      if (xhr.status === 200) {
        data = JSON.parse(xhr.responseText);
      }
      country = data.lookup[country];
      this.site = data.sites[country];
      this.cart = data.carts[country];
      Digikey.__super__.constructor.call(this, "Digikey", country);
    }

    Digikey.prototype.clearCart = function() {
      var clear_url, that;
      that = this;
      if (/classic/.test(this.cart)) {
        clear_url = "https" + this.site + "/classic/Ordering/OrderingHome.aspx";
        return chrome.tabs.create({
          "url": clear_url
        }, function(temp_tab) {
          var code;
          code = "document.forms[1].elements['ctl00_mainContentPlaceHolder_btnCreateNewOrder'].click();";
          return chrome.tabs.executeScript(temp_tab.id, {
            "code": code
          }, function() {
            var check_done, done;
            done = false;
            check_done = setInterval(function() {
              return chrome.tabs.get(temp_tab.id, function(temp_tab_after_execute) {
                if ((new RegExp(this.cart)).test(temp_tab_after_execute.url)) {
                  clearInterval(check_done);
                  chrome.tabs.remove(temp_tab_after_execute.id);
                  chrome.tabs.query({
                    "url": "*" + that.site + "/classic/*rdering/*dd*art.aspx*"
                  }, function(tabs) {
                    var tab, _i, _len, _results;
                    _results = [];
                    for (_i = 0, _len = tabs.length; _i < _len; _i++) {
                      tab = tabs[_i];
                      _results.push(chrome.tabs.reload(tab.id));
                    }
                    return _results;
                  });
                  done = true;
                  return Digikey.__super__.clearCart.call(this, that);
                }
              });
            }, 100);
            return setTimeout(function() {
              if (!done) {
                console.error(that.name + " cart clearing failed.");
                return clearInterval(check_done);
              }
            }, 5000);
          });
        });
      } else if (/ShoppingCartView/.test(this.cart)) {
        throw new Error("Not implemented");
      }
    };

    return Digikey;

  })(Retailer);

}).call(this);
